AWSTemplateFormatVersion: "2010-09-09"
 
Description: Daily update database
 
Resources:
  RestApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Body:
        Fn::Transform:
          Name: 'AWS::Include'
          Parameters:
            Location: 'docs/swagger.yaml'
      Name: RestApiGateway

Outputs:
  RestApiGatewayId:
    Value: !Ref RestApiGateway
    Export:
      Name: !Sub ${AWS::StackName}-RestApiGatewayId