AWSTemplateFormatVersion: "2010-09-09"
 
Description: Daily update database
 
Resources:
  DbUpdateRole:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: String
      PathPart: String
      RestApiId: String