AWSTemplateFormatVersion: "2010-09-09"
 
Description: Record table

Resources: 
  ParsonalRecordsTable:
    Type : AWS::DynamoDB::Table
    Properties:
      TableName: PersonalRecordsTable
      AttributeDefinitions: 
        - AttributeName: HashKey
          AttributeType: S
      KeySchema:
        - AttributeName: HashKey
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 2
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - { Key: version, Value: 1.0 }
  
  TeamRecordsTable:
    Type : AWS::DynamoDB::Table
    Properties:
      TableName: TeamRecordsTable
      AttributeDefinitions: 
        - AttributeName: HashKey
          AttributeType: S
      KeySchema:
        - AttributeName: HashKey
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - { Key: version, Value: 1.0 }