AWSTemplateFormatVersion: "2010-09-09"
 
Description: Record table

Resources: 
  PitcheRecordsTable:
    Type : AWS::DynamoDB::Table
    Properties:
      TableName: PitchRecordsTable
      AttributeDefinitions: 
        - AttributeName: HashKey
          AttributeType: S
        - AttributeName: RangeKey
          AttributeType: S
      KeySchema:
        - AttributeName: HashKey
          KeyType: HASH
        - AttributeName: RangeKey
          KeyType: RANGE
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 2
      GlobalSecondaryIndexes:
        - IndexName: YearIndex
          KeySchema:
            - AttributeName: GSI1HashKey
              KeyType: HASH
            - AttributeName: GSI1RangeKey
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 1
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  HitRecordsTable:
    Type : AWS::DynamoDB::Table
    Properties:
      TableName: HitRecordsTable
      AttributeDefinitions: 
        - AttributeName: HashKey
          AttributeType: S
        - AttributeName: RangeKey
          AttributeType: S
      KeySchema:
        - AttributeName: HashKey
          KeyType: HASH
        - AttributeName: RangeKey
          KeyType: RANGE
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 2
      GlobalSecondaryIndexes:
        - IndexName: YearIndex
          KeySchema:
            - AttributeName: GSI1HashKey
              KeyType: HASH
            - AttributeName: GSI1RangeKey
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 1
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
  
  TeamRecordsTable:
    Type : AWS::DynamoDB::Table
    Properties:
      TableName: TeamRecordsTable
      AttributeDefinitions: 
        - AttributeName: HashKey
          AttributeType: S
      KeySchema:
        - AttributeName: HashKey
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true