AWSTemplateFormatVersion: "2010-09-09"
 
Description : "Daily update database"
 
Resources:
  UpdateDbFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: record
        S3Key: module/daily_updatedb.zip
      FunctionName: DailyUpdateDb
      Handler: lambda_function.lambda_handler
      MemorySize: 256
      ReservedConcurrentExecutions: 2
      Role: timely-FunctionRole #arn
      Runtime: python3.6
      Timeout: 60
      Tags: 
        - { Key: varsion, Value: 1.0 }