


Resources:
  FunctionRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        JSON object
      ManagedPolicyArns:
        - 文字列
      MaxSessionDuration: Integer
       Path: String
      Policies:
        - Policies
      RoleName: timely-FunctionRole