AWSTemplateFormatVersion: "2010-09-09"
 
Description : web and module bucket

Resources:
  module:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private
      BucketName: record-module
      LoggingConfiguration:
        DestinationBucketName: log
        LogFilePrefix: record/module/
      Tags:
        - { Key: version, Value: 1.0 }

  web:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: PublicRead
      BucketName: record-web
      LoggingConfiguration:
        DestinationBucketName: log
        LogFilePrefix: record/web/
      Tags:
        - { Key: version, Value: 1.0 }
      WebsiteConfiguration:
        ErrorDocument: error.html
        IndexDocument: index.html

  log:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private
      BucketName: common-log
      Tags:
        - { Key: version, Value: 0.0 }