AWSTemplateFormatVersion: "2010-09-09"
 
Description : web and module bucket

Resources:
  # module:
  #   Type: AWS::S3::Bucket
  #   DependsOn: log
  #   Properties: 
  #     AccessControl: Private
  #     BucketName: records-module
  #     LoggingConfiguration:
  #       DestinationBucketName: !Ref log
  #       LogFilePrefix: records/module/
  #     Tags:
  #       - { Key: version, Value: 1.0 }

  RecordsWeb:
    Type: AWS::S3::Bucket
    DependsOn: RecordsWebLog
    Properties: 
      AccessControl: PublicRead
      BucketName: records-web-hogeeee
      LoggingConfiguration:
        DestinationBucketName: !Ref RecordsWebLog
        LogFilePrefix: records/web/
      Tags:
        - { Key: version, Value: 1.0 }
      WebsiteConfiguration:
        ErrorDocument: error.html
        IndexDocument: index.html

  RecordsWebLog:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: LogDeliveryWrite
      BucketName: records-web-hogeeee-log
      Tags:
        - { Key: version, Value: 0.0 }

  WebPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: 
        Ref: RecordsWeb
      PolicyDocument:
        Statement:
        -
          Sid: PublicReadForGetBucketObjects
          Action: s3:GetObject
          Effect: Allow
          Principal: '*'
          Resource:
            Fn::Join:
            - ""
            -
              - "arn:aws:s3:::"
              -
                Ref: RecordsWeb
              - "/*"
          # Condition:
          #   StringLike:
          #     aws:Referer:
          #       - http://www.example.com/*
          #       - http://example.com/*