swagger: "2.0"
basePath: "/"
schemes:
  - "https"
produces: ['application/json']
consumes: ['application/json']
x-amazon-apigateway-gateway-responses:
  MISSING_AUTHENTICATION_TOKEN:
    statusCode: 404
    responseTemplates:
      application/json: |
        {"message":"Not Found"}
  THROTTLED:
    statusCode: 503
    responseTemplates:
      application/json: |
        {"message":"Too many requests"}
paths:
  /api/records/v1/hitter/{personalId}:
    parameters:
      - tbd
  
    get:
      summary: get hitter record
      description: get hitter record
      parameters: 
        - name: year
          in: query
          type: string
          maxLength: 256
      responses:
        200:
          description: hitter year records
          headers: 
            Data:
              type: string
              description: 応答時間
          schema:
            $ref: '#/definitions/hitterRecords'
        400:
        404:
        500:

  definitions:
    hitterRecords: 
      type: object
      description: hitter records
      required:
        -
      properties:
        name:
          type: string
        year:
          type: string
        team:
          type: string

    hitterTotalRecords:
      type: array
      description: hitter total records
      items:
        $ref: '#/definitions/hitterRecords'

    yearHitterRecords:
      type: array
      description: year all hitter rexords
      items:
        $ref: '#/definitions/hitterRecords'

# GET/PUT one's year records
## /api/records/v1/personal/{personalId}
# GET/PUT year all records (def)
## /api/records/v1/pitchers/{year}
## /api/records/v1/hitters/{year}
# GET one's all records
## /api/records/v1/personal_all/{personalId}